### ISSUE TITLE
Page contents

### ISSUE THREAD

**Issue by odinuv** [keboola/developers-docs#11]
Udelat moznost vlozit do stranky obsah (podobne jako na wiki), nemeleo by to byt automaticky u vsech  stranek, jen u tech delsich, kde to ma smysl (cili asi rucne vlozit nejaky tag, ze se to tam ma vygenerovat?)

**Comment by ujovlado** [comment]
@odinuv jekyll pouziva kramdown, cize je to celkom easy, toto pridas a mas.
```kramdown
Contents

* whatever
{:toc}
```
http://kramdown.gettalong.org/converter/html.html#toc

Napr.:
![screenshot_2016-03-25_22-46-56](https://cloud.githubusercontent.com/assets/419849/14054708/aafa77d2-f2db-11e5-9529-c03d29e06ee1.png)

**Comment by ondrejhlavacek** [comment]
No pecka!!! :-)

**Comment by odinuv** [comment]
merged in e65959892bfac31c905a30a32b084103281c8656
