### ISSUE TITLE
logging/#gelf-logger is missing JSON configuration example

### ISSUE THREAD

**Issue by davidesner** [keboola/developers-docs#114]
The https://github.com/keboola/developers-docs/blob/master/extend/common-interface/logging.md#setting-up page is missing example of JSON configuration that is needed in Developer portal.

Something like 
```json
{
  "verbosity": {
    "100": "none",
    "200": "normal",
    "alert": "camouflage",
    "error": "verbose",
    "notice": "normal",
    "warning": "normal",
    "critical": "camouflage",
    "emergency": "camouflage"
  },
  "gelf_server_type": "tcp"
}

**Comment by odinuv** [comment]
https://keboola.atlassian.net/browse/DOCS-46
