### ISSUE TITLE
Embed API docs?

### ISSUE THREAD

**Issue by Halama** [keboola/developers-docs#16]
Seznam všech našich aktuálních API dokumentací a rovnou jejich embed jako např. https://developer.gooddata.com/api#/reference/projects/invite-a-user-to-a-project/disable-a-user nebo https://developers.csas.cz/html/devs/net-banking.html

**Comment by ujovlado** [comment]
Fixed in 82ae40599b6439ea96cd2fe5ebfad31bc52a6368 (nakoniec sme sa na offsite dohodli, ze sa to nebude embedovat)
