### ISSUE TITLE
Tune for mobile, make responsive

### ISSUE THREAD

**Issue by ujovlado** [keboola/developers-docs#20]
- [x] TOC
- [x] Turn off Bootstrap Affix on mobile
- [x] Smaller paddings
- [x] ~~Bigger font~~ LGTM
- [x] Responsive images (`.img-responsive`)
- [x] ~~Responsive image popups (minor?)~~ LGTM
- [x] Async font loading (check it)

**Comment by odinuv** [comment]
@ujovlado je tohle jeste aktualni ?

**Comment by ujovlado** [comment]
pozrem len ci ide ten font async a zavrem to ...

**Comment by ujovlado** [comment]
ok, toto tu zavrem ale FOUT este doriesime v dalsom issue.
