### ISSUE TITLE
Docker runner /data/in/tables

### ISSUE THREAD

**Issue by Halama** [keboola/developers-docs#35]
V dokumentaci se říká že to defaultně pojmenuje soubory `{tableId}.csv` https://github.com/keboola/developers-docs/blob/ab329332e1b2258eb03d7792969215993553bd87/extend/common-interface/folders.md#dataintables-folder

Podle všeho to ale pojmenuje jenom `{tableId}`. 

![image](https://cloud.githubusercontent.com/assets/903531/24706622/9983ef44-1a10-11e7-8e33-168968f2c8eb.png)

![image](https://cloud.githubusercontent.com/assets/903531/24706627/9dd3e180-1a10-11e7-98ee-dd5da0cac5c2.png)

**Comment by Halama** [comment]
Obejdu to takhle 
![image](https://cloud.githubusercontent.com/assets/903531/24706770/39202856-1a11-11e7-826f-9e064e1bea3d.png)


ale trochu mě to zmátlo.

**Comment by ondrejhlavacek** [comment]
jj, input mapping říká, že to je bez CSV 

![image](https://cloud.githubusercontent.com/assets/497675/24706958/0f2786d8-1a12-11e7-9204-c79942d363e6.png)

**Comment by Halama** [comment]
ok, upravím to teda v té dokumentaci?

**Comment by ondrejhlavacek** [comment]
jestli to máš u ruky, tak jo, super, dík!
