### ISSUE TITLE
Docker Runner sync actions API url

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developers-docs#39]
v dokumentaci není explicitně uvedený, že posílání requestů na sync api musí jít přes https://docker-runner.keboola.com/

na https://developers.keboola.com/extend/common-interface/actions/ je uveden ještě starej https://syrup-docker.keboola.com

![image](https://cloud.githubusercontent.com/assets/497675/26346599/0804bc58-3fa7-11e7-9d37-75e7f4b86364.png)

**Comment by odinuv** [comment]
fixed in b76ed19dc369aac3661bb44a3ef4c5ecc7c9a94a
