### ISSUE TITLE
Describe regions and endpoints

### ISSUE THREAD

**Issue by Halama** [keboola/developers-docs#49]
Všude v dokumentaci pracujeme s endpointy pro default us east stack.
Asi by bylo dobrý přidat stránku kde budou popsány všechny endpointy pro jednotlivé stacky.
Neco ve stylu http://docs.aws.amazon.com/general/latest/gr/rande.html

Matejkys se ted ptal:

> prosím tě, jaký je endpoint GD Writeru v EU projektech? když se se svým tokenem dotazuji na `https://syrup.keboola.com/gooddata-writer/v2/`, tak mi to hlásí invalid token, ale ten mám určitě správně

**Comment by odinuv** [comment]
note to self: https://connection.keboola.com/v2/storage `services`
