### ISSUE TITLE
navigation drilldown

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developers-docs#5]
https://github.com/keboola/developers-docs/blob/gh-pages/_includes/navigation.html

ať se nějak rozbaluje

**Comment by odinuv** [comment]
první (a možná i druhá) úroveň by měly být vždy rozbalené

**Comment by ujovlado** [comment]
V #9 je uz urobena cast, kde ti to rozbaluje podla toho ako klikas + je videt vzdy len aktivnu cast stromu

**Comment by odinuv** [comment]
Merged in 3b278555dafed0118e646f66e275d90bc6deb71d

Sice jsem si to predstavoval jinak, ale takhle to vypada dobre, nechame to chvilku ulezet.
