### ISSUE TITLE
Fix FOUT (unstyled text)

### ISSUE THREAD

**Issue by ujovlado** [keboola/developers-docs#54]
![screenshot_2017-11-27_11-58-25](https://user-images.githubusercontent.com/419849/33263482-51b8739c-d36a-11e7-9dc9-756288530d73.png)

We should apply classes (set Lato font) to document after font is loaded.

**Comment by janmichek** [comment]
Chapu, ale co je cílem / motivací issue?

**Comment by ujovlado** [comment]
Ved je to tu napisane. Opravit to, nech tam nie je FOUT pri nacitavani stranky.

**Comment by janmichek** [comment]
Milé :) omlouvam se za retardovanou otázku. Příště lépe přečtu

**Comment by ujovlado** [comment]
Tu som sa kopol, mame tam FOIT (invisible text), nie FOUT (unstyled text). Vyriesi sa to pridanim webfont loadera. Bude tam sice prave spominany FOUT no nestane sa, ze by to clovek videl bez textu.
