### ISSUE TITLE
distinguish developers.keboola.com and help.keboola.com

### ISSUE THREAD

**Issue by odinuv** [keboola/developers-docs#6]
Udělat dominantní nějakou jinou barvu, aby bylo jasný, že se člověk přesunul z jednoho na druhý

**Comment by odinuv** [comment]
@ondrejhlavacek http://help.keboola.com/ ? neni to moc kriklavy?

**Comment by Halama** [comment]
Nebude lepsi to postavit na uplne novem layoutu (bootstrapu). Ten z toho KBC neni moc responzivni atd...

**Comment by odinuv** [comment]
Ted resim jak to bude vypadat, jak to CSSko bude udelany je vedlejsi

**Comment by ondrejhlavacek** [comment]
@odinuv no tyjo, to dost! :-)
udělal bych to tak, jak jsou na tý stránce všechny věci domodra (pozadí pod navigací, odkazy), tak by se jenom šouplo `hue` na jinou barvu, a udělal bych to spíš na developers.keboola.com než na help.keboola.com, která by spíš měla ctít rodný barvy

zkusím nahodit zelenou

**Comment by odinuv** [comment]
jo, taky bych to udelal spis na developers.keboola.com, jen jsem to chtel vyzkouset :) Ale zelenou no nevim no...

**Comment by ondrejhlavacek** [comment]
@odinuv nahodil jsem, je možný to přes hue v cssku nastavit na cokoliv jinýho :-)

**Comment by ondrejhlavacek** [comment]
klidně revertuj / commitni znovu

**Comment by odinuv** [comment]
to je ale ohyzdna barva :D

**Comment by ondrejhlavacek** [comment]
docela jo no, ale je to ready na přebarvení na cokoliv :-)

**Comment by odinuv** [comment]
solved by 79469bff8024e5d30aed937b95538e388211f776

**Comment by ondrejhlavacek** [comment]
jenom bych udělal aktivní text v navigaci trochu světlejší
