### ISSUE TITLE
slightly different style

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developers-docs#64]
develoers.keboola.com has larger paragraph padding and larger headline text size (not the main headline)

![http://g.recordit.co/dfbEPrXMKW.gif](http://g.recordit.co/dfbEPrXMKW.gif)

**Comment by ujovlado** [comment]
I'll diff it and fix, or if it was only one commit, we can do cherry-pick ... both docs site have the same base

**Comment by odinuv** [comment]
and which one is better ? :)

**Comment by ujovlado** [comment]
It's not about padding, it's about `h3` vs `h4` ;)

**Comment by ujovlado** [comment]
So, I'll change it in `help.keboola.com` to `h4`

**Comment by odinuv** [comment]
in dev docs fixed in 2f54fc074141128444aa47b4afc651a47b4b160c

**Comment by ujovlado** [comment]
I hope you meant only that index page :)
