### ISSUE TITLE
config rows, processors

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developers-docs#65]
najlos [2:09 PM]
@odin začínám psát dokumentaci pro S3 extraktor, zmíním tam procesory a jak na ně a upravil bych trochu víc developers dokumentaci, kde bych udělal komplet seznam všech procesorů (s krátkým popiskem a linkama na repo) a udělal nějakej guide, jak napsat vlastní procesor?

odin [2:12 PM]
no je tam ted nove https://github.com/keboola/developers-docs/blob/refactor/extend/component/tutorial/processors.md na konfiguraci
seznam procesoru bych nedelal - to zas bude muset udrzovat a muzes si je celkem snadno vypsat - https://github.com/keboola/developers-docs/blob/refactor/extend/component/processors.md#available-processors
v cem bys rekl, ze se lisi procesor od jine komponenty?

najlos [2:13 PM]
technicky v ničem, je to jen jinej mindset
1:1, n:1, 1:n, předávání manifestů, takový ty best practices, co jsme zatím vyzkoumali

odin [2:14 PM]
nehodilo by se to spis sem https://github.com/keboola/developers-docs/blob/refactor/extend/component/implementation.md ?

najlos [2:15 PM]
jo, klidně!
rovnou bych tam napsal, jak má vypadat komponenta, která má umět procesory, možná bych začal dokumentovat i config rows?
nemám teda počkat až to mergneš? end user dokumentace má prioritu, se zbytkem klidně počkám

odin [2:19 PM]
jo, asi bych zacal tim config rows
chtel jsem jeste pockat na mateje jestli to da, ale mozna to mergnu i tak

najlos [2:20 PM]
to nemá v UI zatím žádný vychytávky jako ostatní komponenty (ui flags)
ale můžu to rozepsat tak jako tak a pak se to bude doplňovat
s developers dokumentací nespěchám, takže úplně v klidu

odin [2:22 PM]
no s tema rows by se asi dalo zacit tady https://github.com/keboola/developers-docs/blob/refactor/integrate/storage/api/configurations.md
to tam vlastne vubec neni popsany

najlos [2:24 PM]
nj!
začnu teda až to mergneš?

**Comment by ondrejhlavacek** [comment]
tak prej to udělá @odinuv

**Comment by odinuv** [comment]
done 68385a3e4de692ff7a9565ede25441aafe52ae2b
