### ISSUE TITLE
Better Search

### ISSUE THREAD

**Issue by odinuv** [keboola/developers-docs#69]

**Comment by ujovlado** [comment]
Funguje to, staci doladit ako to vyzera:

![selection_017](https://user-images.githubusercontent.com/419849/37080315-1abdcd5e-21e6-11e8-9bad-cc8296599109.png)

Viac info postnem sem.

**Comment by ujovlado** [comment]
Tak uz to vyzera lepsie a funguje to paradne

![selection_018](https://user-images.githubusercontent.com/419849/37080933-25727e0a-21e8-11e8-9b70-b505343e0c5f.png)


![selection_018](https://user-images.githubusercontent.com/419849/37080869-e4230b68-21e7-11e8-

**Comment by odinuv** [comment]
looks cool

**Comment by ujovlado** [comment]
Len pre evidenciu

> Hi there, 
> 
> Congratulations, your search is now ready! 
> I've successfully configured the underlying crawler and it will now run every 24h. 
> 
> You're now a few steps away from having it working on your website: 
> - Copy the following CSS/JS snippets and add them to your page 
> 
>  
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" /> 
>  
> <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script> 
> <script type="text/javascript"> docsearch({ 
>  apiKey: '157049a881510c7a785af33a79362421', 
>  indexName: 'keboola_developers', 
>  inputSelector: '### REPLACE ME ####', 
>  debug: false // Set debug to true if you want to inspect the dropdown 
> }); 
> </script> 
> 
> - Add a search input if you don't have any yet, and update the inputSelector value in the code snippet to a CSS selector that targets your input field. 
> - Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/) 
> - You can also check your configuration in the github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/keboola_developers.json). Feel free to open pull requests! 
> 
> Feel free to get back to us if you have any issues or questions regarding the integration. 
> We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it. 
> 
> Have a nice day :)

**Comment by ujovlado** [comment]
^ Podstatna je ta cast, kde pise, ze si to mozeme doladit poslanim PR:

> You can also check your configuration in the github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/keboola_developers.json). Feel free to open pull requests!
