### ISSUE TITLE
Run orchestration by API

### ISSUE THREAD

**Issue by Halama** [keboola/developers-docs#86]
Poměrně častý use case a lidé netuší že to jde. Popsat např. sem https://developers.keboola.com/integrate/ ?

**Comment by Halama** [comment]
souvisí s https://github.com/keboola/kbc-ui/issues/1876

**Comment by odinuv** [comment]
related https://github.com/keboola/developers-docs/issues/87

**Comment by odinuv** [comment]
https://keboola.atlassian.net/browse/DOCS-35
