### ISSUE TITLE
Sync actions documentation

### ISSUE THREAD

**Issue by ujovlado** [keboola/developers-docs#88]
Issues:
- It is not clear that sync action should return json in specific format to respond with "success"
- it is not clear that status can be one of "success" or "ok"

https://github.com/keboola/kbc-ui/blob/a61f9c89dae82155ac35fef6958607a1a68c0e37/src/scripts/react/common/TestCredentialsButtonGroup.coffee#L69

sample (encoded to json in RunCommand):
https://github.com/keboola/dynamodb-extractor/blob/8cacf3db2ffdd38c9d9f7cd8a90940b4fa29bb77/src/Keboola/DynamoDbExtractor/Extractor.php#L52

cc: @Actimel

**Comment by odinuv** [comment]
this is UI thing, nothing to do with component development, component can return anything

**Comment by odinuv** [comment]
bych to zavrel @ujovlado

**Comment by ujovlado** [comment]
Ok, got it. But components are working with our UI ... it I create component which is not "compliant" with UI (not returning proper structure) it will not work.

**Comment by odinuv** [comment]
> if I create component which is not "compliant" with UI ... it will not work.
 
it will not work either way, because currently, the UI has to be enabled for that component manually

**Comment by ujovlado** [comment]
Yep, I agree ... also there's process for approving in devportal-ui. ok then. :+1:
