### ISSUE TITLE
Add section regarding License for components

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/developers-docs#94]
* what it's supposed to contain
* why just putting MIT there is not enough
* add license templates for different kinds of compoments (writers, extractors, apps, apps that send data elsewhere, etc.)
* add a link to docs from the License field in developer-portal-ui

Related: https://github.com/keboola/developer-portal/issues/255

**Comment by odinuv** [comment]
https://keboola.atlassian.net/browse/DOCS-56
